//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEmpresa.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        public string ben_tipoIdentificacion { get; set; }
        public string ben_idTrabajador { get; set; }
        public string ben_identificacion { get; set; }
        public string ben_nombreCompleto { get; set; }
        public string ben_geneto { get; set; }
        public string ben_fechaNacimiento { get; set; }
        public string ben_direccion { get; set; }
        public string ben_telefono { get; set; }
        public string ben_email { get; set; }
    
        public virtual Trabajador Trabajador { get; set; }
    }
}
