//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEmpresa.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoDetalle
    {
        public string detcon_fecha { get; set; }
        public string detcon_hora { get; set; }
        public string detcon_descripcion { get; set; }
        public Nullable<int> detcon_idMotivo { get; set; }
        public string detcon_resultado { get; set; }
        public string detcon_idEmpresa { get; set; }
        public string detcon_idTrabajador { get; set; }
        public string detcon_id { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Motivo Motivo { get; set; }
    }
}
