//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEmpresa.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public int suc_id { get; set; }
        public string suc_nombre { get; set; }
        public string suc_direccion { get; set; }
        public string suc_telefono { get; set; }
        public string suc_idencargado { get; set; }
        public string suc_encargado { get; set; }
        public string suc_idEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
